#注意：如果在记事本上编写，下面的缩进不要使用Tab来缩进，不然报错
spring:
  profiles:
    active: dev # 激活开发环境配置
---
server:
  port: 6001 #端口号
spring:
  profiles: dev1 # 开发环境
  application:
    name: microservice-config-eureka

eureka:
  instance:
    hostname: eureka6001.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka6002.com:6002/eureka/
  server: 
    enable-self-preservation: false # 禁用自我保护机制*****************
---
server:
  port: 6001 #端口号
spring:
  profiles: prod1 # 开发环境
  application:
    name: microservice-config-eureka6001

eureka:
  instance:
    hostname: 192.168.1.128
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:6002/eureka/
    server: 
      enable-self-preservation: true # 开启自我保护机制*****************
     
---
server:
  port: 6002 #端口号
spring:
  profiles: dev2 # 开发环境
  application:
    name: microservice-config-eureka6002

eureka:
  instance:
    hostname: eureka6002.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka6001.com:6001/eureka/
    server: 
      enable-self-preservation: false # 禁用自我保护机制*****************
---
server:
  port: 6002 #端口号
spring:
  profiles: prod2 # 开发环境
  application:
    name: microservice-config-eureka6002

eureka:
  instance:
    hostname: 192.168.1.128
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:6001/eureka/
    server: 
      enable-self-preservation: true # 开启自我保护机制*****************

